Repository vegaprotocol/vegawallet-desktop, pull requests merged in 2022-09, with the labels that each got.

#303 chore: remove apollo client setup and fetching of asset data
  .github/workflows/build-binaries.yml
  .github/workflows/release-binaries.yml
  frontend/automation/cypress/support/commands.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/key-pair-list/key-pair-list.tsx
  frontend/src/hooks/use-accounts.ts
  frontend/src/lib/apollo-client.ts
  frontend/src/routes/home/home.tsx
  frontend/src/routes/wallet/keypair/home.tsx
  frontend/src/routes/wallet/wallet.tsx
  frontend/src/wailsjs/go/models.ts
  frontend/src/wailsjs/runtime/package.json
  frontend/src/wailsjs/runtime/runtime.d.ts
  frontend/src/wailsjs/runtime/runtime.js
Labels: no-issue

#306 chore: update add issue to project action
  .github/workflows/add_issue_to_project.yml
Labels: desktop-wallet

#335 Migrate to Go 1.19
  go.mod
Labels: desktop-wallet, no-changelog, no-issue
